# Generated by Django 3.2.7 on 2021-09-15 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consult',
            fields=[
                ('consult_id', models.AutoField(db_column='consult_ID', primary_key=True, serialize=False)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'consult',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('doctor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('specialization', models.CharField(max_length=100)),
                ('contactno', models.CharField(db_column='contactNo', max_length=15)),
            ],
            options={
                'db_table': 'doctors',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('patient_id', models.IntegerField(db_column='patient_ID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('insurance', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=100)),
                ('contactno', models.CharField(db_column='contactNo', max_length=15)),
            ],
            options={
                'db_table': 'patients',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Performed',
            fields=[
                ('result_id', models.AutoField(db_column='result_ID', primary_key=True, serialize=False)),
                ('result', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'performed',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('test_id', models.IntegerField(primary_key=True, serialize=False)),
                ('test_name', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('duration', models.IntegerField(db_column='duration')),
            ],
            options={
                'db_table': 'tests',
                'ordering': ('test_id',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('record_id', models.AutoField(db_column='record_ID', primary_key=True, serialize=False)),
                ('consult', models.ForeignKey(db_column='consult_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='myapp1.consult')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp1.doctors')),
                ('patient', models.ForeignKey(db_column='patient_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='myapp1.patients')),
                ('result', models.ForeignKey(db_column='result_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='myapp1.performed')),
                ('test', models.ForeignKey(db_column='test_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='myapp1.tests')),
            ],
            options={
                'db_table': 'records',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='consult',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp1.doctors'),
        ),
        migrations.AddField(
            model_name='consult',
            name='patient',
            field=models.ForeignKey(db_column='patient_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='myapp1.patients'),
        ),
        migrations.AddField(
            model_name='consult',
            name='test',
            field=models.ForeignKey(db_column='test_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='myapp1.tests'),
        ),
    ]
