# Generated by Django 3.2.7 on 2021-10-12 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0002_auto_20211012_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='email',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
