# Generated by Django 3.2.7 on 2021-10-12 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0004_alter_patients_patient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='doctor_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tests',
            name='test_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
